README.md

- **Zankyou no Terror**: 
- **https://myanimelist.net/anime/23283/Zankyou_no_Terror**: 
It has a simple but good story, and there a hacking scene in this anime.

Add Zankyou no Terror to README.md

---

README.md

- **Title**: Koukaku Kidoutai / Ghost in Shell
- **Link**: https://myanimelist.net/anime/43/Koukaku_Kidoutai
Some of characher of this anime are programmer/hacker

menambahkan ghost in shell

---

README.md

- **Title**: Steins;Gate
- **Link**: https://myanimelist.net/anime/9253/Steins_Gate
The story is heavily based in sci-fi themes, many of which rely on a hacker character and computers.

Add Steins;Gate

---

README.md

- **Title**:  Dagashi Kashi
- **Link**: https://myanimelist.net/anime/31636/Dagashi_Kashi
It has the iconic coding scene (Javascript one).

added Dagashi Kashi to the list

---

README.md

- **Title**: Cowboy Bebop
- **Link**: https://myanimelist.net/anime/1/Cowboy_Bebop
Sudah jelas dengan score rating yang tinggi 8.79, Cowboy Bepop adalah tontonan anime wajib untuk developer. Anime legendaris ini punya cerita yang menarik, dibuat pada tahun 1998 menceritakan gambaran masa depan yaitu tahun 2071. Menariknya lagi beberapa cerita dalam anime tersebut sudah terjadi pada tahun-tahun ini. Penasaran ? langsung saja tonton.

Cowboy Bepop

---

README.md

- **Title** :Battle Programmer Shirase
- **Link**: https://myanimelist.net/anime/579/Battle_Programmer_Shirase
in this anime a hacker who doesn't want to work for money but he hacks because he just wants to be happy

 Add anime BPS Battle Programmer Shirase

---

README.md

- **Title**: Sewayaki Kitsune no Senko-san
- **Link**: https://myanimelist.net/anime/38759/Sewayaki_Kitsune_no_Senko-san
The main character **Kuroto Nakano** is a programmer. He work in company doing coding. But, at daily life.. he live alone and lonely man.
Note: Solve issue https://github.com/ardianta/anime-for-dev/issues/15

Add anime Sewayaki Kitsune no Senko-san

---

README.md

- **Title**: Kamisama no Memochou (Heaven's Memo Pad)
- **Link**: [https://myanimelist.net/anime/23283/Zankyou_no_Terror](https://myanimelist.net/anime/23283/Zankyou_no_Terror)
The story is based on a mystery, where the main character is a hacker to do an investigation.

Added Kamisama no Memochou

---

README.md

- **Title**: The Animatrix
- **Link**: https://myanimelist.net/anime/1303/The_Animatrix
As the prequel of the matrix movie, this anime taking the theme of the world in computers, hackers, and the struggle of humans against robots.

Add The Animatrix anime.

---

README.md

- **Title**: Persona 5 the Animation 
- **Link**: https://myanimelist.net/anime/36023/Persona_5_the_Animation 
the story is good, and one of the characters is a hacker.

add Persona-5-theAnimation

---

README.md

- **Title**: Psycho-Pass
- **Link**: https://myanimelist.net/anime/13601/Psycho-Pass
A science fiction anime on how technology/AI can affect human society and shows the system vulnerability.

add psycho-pass

---

README.md

- **Tonikaku Kawaii** 
- **https://myanimelist.net/anime/41389/Tonikaku_Kawaii** 
Because yuzaki nasa is a professional programmer and he has a beautiful wife named yuzaki tsukasa
Yuzaki Nasa

Add Tonikaku kawaii

---

README.md

- **Title**: Sekirei
- **Link**: https://myanimelist.net/anime/4063/Sekirei

Add anime Sekirei

---

README.md

- **Title**: Chuunibyou demo Koi ga Shitai!
- **Link**: [Click Here](https://myanimelist.net/anime/14741/Chuunibyou_demo_Koi_ga_Shitai)
**Why this anime should be watched by the developer?**
Chuunibyous are usually the antisocial types, ones with the "cool" factor, and ones who admire mystical powers and recreates them in reality through their imagination.
It's relevant for self-growth and improvement where there were embarrassments in our past lives, especially as a developer. It also applies for [the second sequel](https://myanimelist.net/anime/18671/Chuunibyou_demo_Koi_ga_Shitai_Ren)
- **Title**: Chuunibyou demo Koi ga Shitai! Movie: Take On Me
- **Link**: [Click Here](https://myanimelist.net/anime/35608/Chuunibyou_demo_Koi_ga_Shitai_Movie__Take_On_Me)
**Why this anime should be …

Update Chuunibyou & NGNL series

---

README.md

- **Title**: Guilty Crown
- **Link**: [Link](https://myanimelist.net/anime/10793/Guilty_Crown)
Some of character of this anime are programmer/hacker
the anime is very interesting to watch even if it might get annoying at times
and it is in issue  #3

Added Guilty Crown to list

---

README.md
Sword_Art_Online.md

- **Title**: Sword Art Online  
- **Link**: https://myanimelist.net/anime/11757/Sword_Art_Online  
**Why this anime should watched by developer?**  
Dalam anime ini diceritakan sebuah teknologi game VRMMORPG SAO, yang kemudian dari game SAO tersebut dikembangkan menjadi game dengan karakter-karakter yang memiliki kecerdasan buatan. Dengan menonton anime ini mungkin bisa menginspirasi developer untuk mengembangkan teknologi seperti di anime SAO

Menambahkan anime Sword Art Online

---

README.md

- **Title**: Saenai Heroine no Sodatekata 
- **Link**: https://myanimelist.net/anime/23277/Saenai_Heroine_no_Sodatekata 
because this anime tells about the making of a visual novel game, this anime tells the story of making games not only developers who work but there are teams that help such as the promotion team, the game song team,game visual images, and storylines

add Saenai Heroine no Sodatekata

---

README.md

- **Angel Beats!**: 
- **https://myanimelist.net/anime/6547/Angel_Beats**: 
Because this anime is very touching
Yuzuru Otonashi

Menambahkan anime angel beats

---

README.md

!--
Hi there! Thank you for sumbiting a PR!
Before you make PR, please fill this form
-->
- **Title**: Blood-C: The Last Dark
- **Link**: [link]( https://myanimelist.net/anime/10681/Blood-C__The_Last_Dark)
there are 3 characters of this anime are hackers in SIRRUT members  and it is in issue [3#](https://github.com/ardianta/anime-for-dev/issues/3#issue-718138164)

Add Blood C The Last Dark

---

README.md

- **Bungou Stray Dogs**: 
- **https://myanimelist.net/anime/31478/Bungou_Stray_Dogs**: 
Because the story is very interesting and dark
Ada tapi saya lupa wkwk :v

Menambahkan Bungou Stray Dogs dan melengkapi SAO & Steins; Gate

---

README.md

- **Title**:  Fugou Keiji: Balance:Unlimited
- **Link**:  https://myanimelist.net/anime/41120/Fugou_Keiji__Balance_Unlimited
Rekomendasi karena di anime ini ada polisi namanya kanbe daisuke nah dia itu punya saldo uang virtual unlimited dan dia juga punya AI yang bernama HEUSC mirip Jarvis ,Developer akan termotivasi buat bikin AI kaya gitu buat Polisi dan Hacker akan termotivasi buat punya saldo Unlimited
Karakter
Kanbe Daisuke,Kanbe sizue

add balance unlimited

---

README.md

- **Title**: Digimon Adventure
- **Link**: https://myanimelist.net/anime/552/Digimon_Adventure
Because this anime has another world background such as the Internet and one of the characters in this anime is Koushiro Izumi who is a hacker or programmer
this is for issue  #3

Add for anime Digimon Adventure

---

README.md

Add for anime .hack//Sign
- **Title**: .hack//Sign
- **Link**: https://myanimelist.net/anime/48/hack__Sign
Background stories in MMORPG games, related to game developers.
#3

Add anime .hack//Sign

---

README.md

- **Kamisama ni Natta Hi**: 
- **https://myanimelist.net/anime/41930/Kamisama_ni_Natta_Hi**: 
Because the world will end in 30 days
Suzuki Hiroto

Menambahkan kamisama ni natta hi

---

README.md

- **Title**:  Hello World
- **Link**: https://myanimelist.net/anime/38816/Hello_World
**Why this anime should be watched by the developer?**
This movie combines romance and sci-fi which inspired by the latest technological advancement: UAV, AR/VR, Quantum Computer, and Space Colonization.  The title itself represents classical jargon of first step into programming world.

update Hello World

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

- **Title**: Hyperdimension Neptunia
- **Link**: https://myanimelist.net/anime/16157/Choujigen_Game_Neptune_The_Animation
There is a hacker in this Anonydeath.
Issue #3

Added Hyperdimension Neptunia

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

- **Title**:Hyouka
- **Link**: https://myanimelist.net/anime/12189/Hyouka
It does not have any hackers or programmers, but think most techies will be able to relate with the energy-conserving, apathetic protagonist, Oreki Houtarou. Also, the way he uses logical reasoning to solve any mystery that comes up is fascinating to watch.

Add Hyouka

---

README.md

- **Title**: Noblesse
- **Link**: [](https://myanimelist.net/anime/41345/Noblesse)
Added to address #52, one of the characters (Tao) programs and hacks

added noblesse

---

README.md

- **Title**: Miss Kobayashi's Dragon Maid
- **Link**: https://myanimelist.net/anime/33206/Kobayashi-san_Chi_no_Maid_Dragon
The main character is a python developer!

add Miss Kobayashi

---

README.md

- **Title**: Mob Psycho 100 
- **Link**: (https://myanimelist.net/anime/32182/Mob_Psycho_100) 
This anime is about a psychic middle school boy who tries to live a normal life and keep his growing powers under control, even though he constantly gets into trouble.As he grows he wants to find his purpose in life and wants to live a happy life.This anime teaches us many values on finding purpose in life and live a happy life.Also this anime has a good sense of humour in it and helps us to relax after completing a busy day.

Add Mob Psycho 100

---

README.md

- **Title**: Zankyou no Terror (Terror in Resonance)
- **Link**: https://myanimelist.net/anime/23283/Zankyou_no_Terror
Main protagonist uses some real-world tools and methods like: TOR, Backdooring, IP camera, Twitter bots, Reverse shell e.t.c.(The guy legit uses `wget`) which is rare since most anime, only shows a character writing some bunch of green line Binary Codes, which is wrong since <strong>us Programmers don't know how to read or write in BINARY CODES</strong>.
<br>
- **Title**: Shinryaku! Ika Musume - The Squid Girl
- **Link**: https://myanimelist.net/anime/8557/Shinryaku_Ika_Musume
After a hectic day of Coding or should I say <strong><em>DEBUGGING your/someone else's …

Added Terror in Resonance and Squid Girl

---

README.md

- **Title**: Cyberpunk: Edgerunners
- **Link**: [Cyberpunk: Edgerunners](https://myanimelist.net/anime/42310/Cyberpunk__Edgerunners)
It is good for developers which are looking to do their careers in metaverse. It shows the world which is highly advanced in the computer world. They can transfer the data directly into each other using memory-chips. Students in their class room practice classwork in virtual environment. People can communicate withput the help of mobiles and other stuff. People can directly do the transactions with memory chips they have installed in. It is perfect anime series for the AR-VR / metaverse developers along with other programmers which like to the things out of the box.

Add Cyberpunk: Edgerunners

---

README.md

- **Title**: Welcome to the NHK - NHK ni Youkoso!
- **Link**: https://myanimelist.net/anime/1210
**Why this anime should be watched by developers?**
This anime is really good for basically everyone to watch. It follows the life of Satou, a hikikomori, which means a total withdrawal from society and seeking extreme degrees of [social isolation] and confinement (source wikipedia). He also believes in conspiracy theories and finds hard to manage real life vs virtual reality life. It´s an existential crisis anime provoking a strong reaction to whoever watches it.  Highly recommend it!

#64 - Added Welcome to the NHK
